---
- hosts: all
  become: true
  tasks:
  - name: Add repository
    yum_repository:
       name: epel
       description: EPEL YUM repo
       baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
       gpgcheck: no

  - name: Install nginx
    yum:
      name: "nginx"
      state: present
      update_cache: yes

  - name: Start nginx
    systemd:
      state: started
      name: nginx

  - name: Enable nginx
    systemd:
      name: nginx
      enabled: yes
      masked: no  
