IMAGE_NAME = "centos/7"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
     v.memory = 512
     v.cpus = 1
    
  end

  config.vm.define "nginx" do |host|
     host.vm.box = IMAGE_NAME
     host.vm.hostname = "nginx"
     host.vm.network "private_network", ip: "10.0.1.4"
     host.vm.provision "ansible" do |ansible|
          ansible.playbook = "nginx-playbook.yml"
     end
  end
end
