---
- hosts: all
  become: true
  tasks:
  - name: create Jenkins repo file 
    file: state=directory path=/etc/yum.repos.d/

  - name: Add repo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/
     
  - rpm_key:
       key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Install jenkins
    yum: 
       name: jenkins
       state: latest
  
